language: android

jdk:
  - oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

branches:
  except:
    - gh-pages
    
cache:
  directories:
    - $HOME/.m2

#after_success:
#  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then ./gradlew build uploadArchives -PNEXUS_USERNAME="${nexusUsername}" -PNEXUS_PASSWORD="${nexusPassword}" -PnexusUsername="${nexusUsername}" -PnexusPassword="${nexusPassword}" ; fi
#

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
